version: "3.9"

services:
  web:
    image: imageapi
    ports:
      - "8000:8000"
    depends_on:
      - chrome
    networks:
      - mynetwork
    environment:
      - SELENIUM_HOST=chrome
      - SELENIUM_PORT=4444
  chrome:
    image: "selenium/standalone-chrome"
    hostname: chrome
    networks:
      - mynetwork
    privileged: true
    shm_size: 2g
    ports:
    - "4444:4444"

networks:
  mynetwork:
    driver: bridge