# Generated by Django 4.1.7 on 2023-03-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0002_alter_patient_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='reporter',
            new_name='service',
        ),
    ]
